### ISSUE TITLE
Notes for grading CI/CD

### ISSUE THREAD

**Issue by HL232** [HL232/bme590final#111]
Hi Dr. Palmeri, Suyash, Dr. Ward, 

Regarding the CI/CD part of grading our final project, we wanted to bring this to your attention:

So before we merge into master, we always make sure the Travis checks pass, like this:

![image](https://user-images.githubusercontent.com/37548303/50036794-c8674f80-ffd9-11e8-86c4-380dae565eeb.png)

However, our database is using mLab, which needs to be cleared every 300 MB or so of storage (because we're using the free tier) Many of our unit tests rely on mLab being functional, so if we reset mLab in the middle of a Travis pytest check, we will get one singular test case failure, like this:

![image](https://user-images.githubusercontent.com/37548303/50036840-1a0fda00-ffda-11e8-8944-0d8d1a5833a0.png)

Therefore, the result is that our `master` branch appears to fail merge checks, when in reality they should pass (here is an example of a successful merge with 0 errors): 

![image](https://user-images.githubusercontent.com/37548303/50036871-4c213c00-ffda-11e8-810d-e0c76a803b14.png)

This isn't something we can control because we HAVE to clear mLab every so often in order to run our code. Please take this into account when grading the CI/CD part of this assignment.

Thanks!

**Comment by mlp6** [comment]
Thanks for the heads up!

**Comment by AznStevy** [comment]
Might I also add that the web server has about 20 endpoints that aren't mentioned in the readme in effort to minimize the data that is transferred between the end user and the web server. The API also allows for a tree structure for image history using the next and previous commands; you can see them in the image object as `parent_id` and `child_ids`. The gui just doesn't happen to use the api to its fullest extent.

**Comment by MattGuptil** [comment]
Finished

**Comment by AznStevy** [comment]
Didn't know you could put a nail in a coffin and dig up a grave all in one action.
