### ISSUE TITLE
Figure out which python library to use for image processing functionality

### ISSUE THREAD

**Issue by HL232** [HL232/bme590final#14]
scikit-image is recommended in the project description

**Comment by HL232** [comment]
I'm using scikit-image for histogram equalization and contrast stretching. I made my own methods for log compression and reverse video but idk if they are right

**Comment by AznStevy** [comment]
Alternatively, for compression, you could use something like this in the pil/pillow library: https://stackoverflow.com/questions/10607468/how-to-reduce-the-image-file-size-using-pil. I recommend pillow (the fork), it's a more mature library.

**Comment by MattGuptil** [comment]
What does the reverse video function do?

**Comment by AznStevy** [comment]
From what I understand, it's just a list of like a binary 2d image and we just need to invert the frames? I'd ask Palmeri tbh.

**Comment by HL232** [comment]
@AznStevy 
K, I'll look into it.
@MattGuptil 
I think it just inverts the colors: https://en.wikipedia.org/wiki/Reverse_video 

Do you guys get my text messages? My phone has been messed up lately and some people don't get my texts

**Comment by HL232** [comment]
@AznStevy 
I'm gonna ask the instructors exactly what they mean by log compression. From what I understand [here](https://homepages.inf.ed.ac.uk/rbf/HIPR2/pixlog.htm) log compression of images can mean literally taking the log of the individual pixel values, so that low pixel values (ie the dark colors) are brightened and the high pixel values (ie the light colors) are dulled. Or is log compression something like compressing the size of the image using PIL/pillow/etc

@mlp6 @suyashkumar @dward2 

Also another question, Reverse Video is what we described it as right? Like inverting colors/frames?

**Comment by mlp6** [comment]
Yep, log compression "compresses" the dynamic range of an image, usually to avoid having a few "extreme" pixels compromise the ability to visualize data over a more limited range of values.

Reverse video is an inversion scheme... usually applied to grayscale images more so than color.  As I mentioned in lecture, you could have your code only apply some of these operations to images of appropriate type.  That is your call on how you would like to handle that, as long as it is explicitly handled.
