### ISSUE TITLE
Update Requirements.txt

### ISSUE THREAD

**Issue by HL232** [HL232/bme590final#15]
at the end of the project, we need to make sure to update the Requirements.txt file with any packages that need to be imported when a user runs our program

**Comment by AznStevy** [comment]
`requirements.txt` has been updated significantly to account for the conversion/header stuff. will merge eventually, but you might want to check it out here 
https://github.com/HL232/bme590final/pull/32/files#diff-b4ef698db8ca845e5845c4618278f29a
