### ISSUE TITLE
App Component refuses to display imported components.. not sure how to fix this. See startingUI branch

### ISSUE THREAD

**Issue by MattGuptil** [HL232/bme590final#21]
Not sure how to fix this, and it sets me at a hard stop because if I can't import components then I don't know what I am doing. Maybe its a syntax error but I can't see it.

**Comment by MattGuptil** [comment]
``import React, { Component } from 'react';
import Button from '@material-ui/core/Button';
import { withStyles } from '@material-ui/core/styles';


class leftSideButtons extends Component {
	render() {
		
		return (
			<div>
				<Button variant="contained" color="primary" >
       			Primary
      			</Button>
      		</div>
		)
	}
}

export default leftSideButtons ;``

**Comment by MattGuptil** [comment]
`import React, { Component } from 'react';
import Button from '@material-ui/core/Button';
import { withStyles } from '@material-ui/core/styles';


class leftSideButtons extends Component {
	render() {
		
		return (
			<div>
				<Button variant="contained" color="primary" >
       			Primary
      			</Button>
      		</div>
		)
	}
}

export default leftSideButtons ;`

**Comment by MattGuptil** [comment]
`import './App.css';
import leftSideButtons from './leftSideButtons' ;
import MuiThemeProvider from 'material-ui/styles/MuiThemeProvider'
import Button from '@material-ui/core/Button';
import axios from 'axios'

class App extends Component {
  render() {
    return (
      <MuiThemeProvider>
      <div>

        <Button variant="contained" color="primary" >
        Upload
        </Button>

        <Button variant="contained" color="primary" >
        Upload
        </Button>





        <leftSideButtons />
      
      </div>
      </MuiThemeProvider>
    );
  }
}

export default App;`

**Comment by mlp6** [comment]
@suyashkumar this is in your domain.  @suyashkumar will be going over ReactJS in more detail during the lecture time today, which may be a great time to bring this up.

**Comment by MattGuptil** [comment]
The issue was that the component name MUST START WITH A CAPITAL LETTER...
