### ISSUE TITLE
Implementing Processing Class

### ISSUE THREAD

**Issue by HL232** [HL232/bme590final#22]
Link to newest commit
6a6127b

Hey Stephen, I have added the basic functionality to the processing.py file you started. A few questions:
How are you implementing this class? Are you making individual instances of Processing, are you passing an image argument into Processing classes, or are you doing something else?

For example:
`a = Processing()`
`a.hist_eq(image)` So you need to pass the image into an instance of Processing as an argument

OR

`a = Processing(image)`
`a.hist_eq()` So that each instance of processing already has an image argument referenced as self.image in the __init__ function. 

I ask cause it'll determine how I structure processing.py. Right now I'm assuming you're doing option 1, so a lot of the `self` arguments aren't actually used, so Pycharm is yelling at me that all the methods may actually be static. 

Also below is my own to-do list, I just needed to write it down somewhere:

- Check with Stephen how he implements this class
- _check_valid_image
- Some of these functions only work with grayscale images
- Check if image processing methods are correct
- Write the unit tests

**Comment by AznStevy** [comment]
The methods themselves could be static, but I just like sticking them in a class. With that said, the former is how I plan to use the class.

**Comment by HL232** [comment]
More questions:
Okay, if you're doing this:
`a = Processing()`
`a.hist_eq(image)`
Is `image` the URL/file name of the picture, or is `image` already converted into the array-like data?

Also for the last function you have in that processing.py file: `def _check_valid_image(self, image)`
Is that supposed to be a separate function, or is that like a special automatic check function?

**Comment by HL232** [comment]
@MattGuptil  @AznStevy 
For documentation:
Today in class, we met and talked about this:
1. Matt's front in GUI takes a user's uploaded image and converts it into Base64 to send to Stephen's Server
2. Stephen converts the Base64 into an image object (numpy matrix)
3. Pass the image object to Howard's Image processing
4. Process the image and return as image object
5. Stephen takes the image object, converts to Base64, and sends back to Matt's GUI
6. Matt decodes Base64 and displays the image
