### ISSUE TITLE
Fix Bug where this.selector function call does not bring up the components

### ISSUE THREAD

**Issue by MattGuptil** [HL232/bme590final#25]

**Comment by MattGuptil** [comment]
In leftSide at line 71 i call this.selector in order to do something. But this function does not run. The browser displays the rest of the webpage but gives me the warning:
 `index.js:1452 Warning: Functions are not valid as a React child. This may happen if you return a Component instead of <Component /> from render. Or maybe you meant to call this function rather than return it.
    in div (at LeftSide.js:70)
    in div (created by Grid)
    in Grid (created by WithStyles(Grid))
    in WithStyles(Grid) (at LeftSide.js:68)
    in div (created by Grid)
    in Grid (created by WithStyles(Grid))
    in WithStyles(Grid) (at LeftSide.js:46)
    in div (at LeftSide.js:44)
    in MuiThemeProviderOld (at LeftSide.js:43)
    in leftSide (at App.js:58)
    in div (at App.js:52)
    in MuiThemeProviderOld (at App.js:50)
    in App (at src/index.js:8)`

**Comment by suyashkumar** [comment]
Can you link to the file and line numbers on the branch in question please?

**Comment by suyashkumar** [comment]
Looking at this right now a couple things:

https://github.com/HL232/bme590final/blob/cb70368021dca85167cd3086a4d31ad7dd2f5546/react-ui/src/leftSide.js#L11

Component names must start with a capital letter, as discussed.

I can't see where you're calling the `selector` function on line 71? Can you update your branch so I can see your latest code?

**Comment by suyashkumar** [comment]
From my response email to you:
> Gotcha, I can't see where you're calling the selector function...it'll be important to see the actual code to debug this, so can you let me know when you get a chance to update the branch? 
> For now, if you're just plopping down {this.selector} in the middle of render, that will not work. You will need to call this.selector() to have it's returned child element placed in the render blob. Is that what you intend? if so try {this.selector()}
> You can also post a permalink to a line or lines of code in the github issue when you get a chance (I believe Mark demonstrated this in class). Doing that will make things super easy to debug for us.

**Comment by MattGuptil** [comment]
Finished
