### ISSUE TITLE
Processing nparray consistency

### ISSUE THREAD

**Issue by AznStevy** [HL232/bme590final#31]
When you work on the processing stuff, please always return an RGB (no alpha) np array from 0-255. It'll help streamline everything else.

**Comment by AznStevy** [comment]
https://github.com/HL232/bme590final/blob/b9b3ccc72070aaf6eaa7f0401c799c44a6b2d7f1/processing.py#L62 example

**Comment by HL232** [comment]
All the processing functions have been changed so that the output is a RGB array of integers in range 0-255. BUT the processing functions only work well for grayscale images. Still working on processing color images.

**Comment by HL232** [comment]
Also watch out cause I merged all of Matt's stuff and Stephen's stuff into my image_processing branch. I hope this doesn't cause conflicts when you pull the changes I made to processing.py
