### ISSUE TITLE
Interesting Processing

### ISSUE THREAD

**Issue by AznStevy** [HL232/bme590final#33]
I think if you have time, you should look into cool things like Gabor filtering, edge detection, contouring, etc. using the scikit-image and opencv (cv2) libraries.

**Comment by AznStevy** [comment]
`pip install python-opencv` for cv2

**Comment by HL232** [comment]
Doubt I'll have time to add additional processing. I'm getting a lot of bugs with my current code so that takes up most of my time. We've already added blurring and sharpening, so I think that's enough.
