### ISSUE TITLE
Using image.io Arrays instead of numpy array?

### ISSUE THREAD

**Issue by HL232** [HL232/bme590final#51]
Hey @AznStevy 

https://github.com/HL232/bme590final/blob/34fd5e227975ba5ffdfce6faa339529e3db3a3a4/img_processor_web_server.py#L466

I was looking at your img_process_webserver.py code. It looks like you're using imageio.imread to read in images right? This outputs an imageio.core.util.Array instead of a numpy array. (although the imageio Array is a subclass of numpy). 

That's fine, I changed all the processing.py files to account for this. As long as we both know about this it should be fine.

**Comment by AznStevy** [comment]
Yeah, imageio handles image files and urls which people have recommended online. Other functions shouldn't be too affected by it. If you're validating based on np.ndarray, i'd get rid of that line lol.
