### ISSUE TITLE
Extension

### ISSUE THREAD

**Issue by AznStevy** [HL232/bme590final#57]
I was wondering if it was possible to get a day-extension on this project without penalty. I have a final on Wednesday which leaves only 1 more day to try to iron out any issues, along with that pdf documentation. Additionally, we need some more time trying to finish the react gui, which is new to all three of us.

**Comment by mlp6** [comment]
@AznStevy To be fair to the class, we would have to extend the deadline for everyone... but I'm inclined to do that b/c the weather is hampering folks' efforts to get together to work on things.  How would Friday at midnight work?
