### ISSUE TITLE
Upload broken

### ISSUE THREAD

**Issue by MattGuptil** [HL232/bme590final#73]
![image](https://user-images.githubusercontent.com/42845359/49849225-8f936480-fda6-11e8-809a-693008e68f29.png)

**Comment by MattGuptil** [comment]
I am currently on branch UIenhance

**Comment by AznStevy** [comment]
Are you still using the same image as before?

**Comment by MattGuptil** [comment]
Yes same image, exact same on as the file I sent you last time

**Comment by MattGuptil** [comment]
Just sent you the image file again

**Comment by MattGuptil** [comment]
Also if you need me immediately please text, I went to bed.
