### ISSUE TITLE
File array issue

### ISSUE THREAD

**Issue by MattGuptil** [HL232/bme590final#89]
![image](https://user-images.githubusercontent.com/42845359/49976214-021f5400-ff0f-11e8-923e-afe96b3f70bc.png)

**Comment by MattGuptil** [comment]
![image](https://user-images.githubusercontent.com/42845359/49976377-9c7f9780-ff0f-11e8-9e83-4c6e0554617a.png)

**Comment by AznStevy** [comment]
https://stackoverflow.com/questions/2720014/upgrading-all-packages-with-pip

**Comment by AznStevy** [comment]
https://i.imgur.com/TKe4eKe.png

**Comment by MattGuptil** [comment]
![image](https://user-images.githubusercontent.com/42845359/49978408-6bf02b80-ff18-11e8-8d23-5fd5af42b6cb.png)

**Comment by MattGuptil** [comment]
![image](https://user-images.githubusercontent.com/42845359/49986083-715f6d00-ff3c-11e8-816f-4dd73a9aee56.png)
